// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auxproxy_grpc_service.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_auxproxy_5fgrpc_5fservice_2eproto__INCLUDED
#define GRPC_auxproxy_5fgrpc_5fservice_2eproto__INCLUDED

#include "auxproxy_grpc_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace auxproxyService {

// The greeting service definition.
class ScaseGrpcSdkService final {
 public:
  static constexpr char const* service_full_name() {
    return "auxproxyService.ScaseGrpcSdkService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Sends a greeting
    // rpc SayHello (HelloRequest) returns (HelloReply) {}
    virtual ::grpc::Status ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::auxproxyService::AuxProxyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> AsyncProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(AsyncProcessReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> PrepareAsyncProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncProcessReadyRaw(context, request, cq));
    }
    virtual ::grpc::Status ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> AsyncActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(AsyncActivateServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> PrepareAsyncActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncActivateServerSessionRaw(context, request, cq));
    }
    virtual ::grpc::Status TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> AsyncTerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(AsyncTerminateServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> PrepareAsyncTerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncTerminateServerSessionRaw(context, request, cq));
    }
    virtual ::grpc::Status ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::auxproxyService::AuxProxyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> AsyncProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(AsyncProcessEndingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>> PrepareAsyncProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncProcessEndingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Sends a greeting
      // rpc SayHello (HelloRequest) returns (HelloReply) {}
      virtual void ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* AsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* PrepareAsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* AsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* PrepareAsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* AsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* PrepareAsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* AsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::auxproxyService::AuxProxyResponse>* PrepareAsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::auxproxyService::AuxProxyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> AsyncProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(AsyncProcessReadyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> PrepareAsyncProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncProcessReadyRaw(context, request, cq));
    }
    ::grpc::Status ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> AsyncActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(AsyncActivateServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> PrepareAsyncActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncActivateServerSessionRaw(context, request, cq));
    }
    ::grpc::Status TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> AsyncTerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(AsyncTerminateServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> PrepareAsyncTerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncTerminateServerSessionRaw(context, request, cq));
    }
    ::grpc::Status ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::auxproxyService::AuxProxyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> AsyncProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(AsyncProcessEndingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>> PrepareAsyncProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>>(PrepareAsyncProcessEndingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) override;
      void ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) override;
      void ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) override;
      void TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)>) override;
      void ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* AsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* PrepareAsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* AsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* PrepareAsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* AsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* PrepareAsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* AsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* PrepareAsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessReady_;
    const ::grpc::internal::RpcMethod rpcmethod_ActivateServerSession_;
    const ::grpc::internal::RpcMethod rpcmethod_TerminateServerSession_;
    const ::grpc::internal::RpcMethod rpcmethod_ProcessEnding_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Sends a greeting
    // rpc SayHello (HelloRequest) returns (HelloReply) {}
    virtual ::grpc::Status ProcessReady(::grpc::ServerContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response);
    virtual ::grpc::Status ActivateServerSession(::grpc::ServerContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response);
    virtual ::grpc::Status TerminateServerSession(::grpc::ServerContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response);
    virtual ::grpc::Status ProcessEnding(::grpc::ServerContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessReady() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessReady(::grpc::ServerContext* context, ::auxproxyService::ProcessReadyRequest* request, ::grpc::ServerAsyncResponseWriter< ::auxproxyService::AuxProxyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestActivateServerSession(::grpc::ServerContext* context, ::auxproxyService::ActivateServerSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::auxproxyService::AuxProxyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTerminateServerSession(::grpc::ServerContext* context, ::auxproxyService::TerminateServerSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::auxproxyService::AuxProxyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessEnding(::grpc::ServerContext* context, ::auxproxyService::ProcessEndingRequest* request, ::grpc::ServerAsyncResponseWriter< ::auxproxyService::AuxProxyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ProcessReady<WithAsyncMethod_ActivateServerSession<WithAsyncMethod_TerminateServerSession<WithAsyncMethod_ProcessEnding<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessReady() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response) { return this->ProcessReady(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessReady(
        ::grpc::MessageAllocator< ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessReady(
      ::grpc::CallbackServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response) { return this->ActivateServerSession(context, request, response); }));}
    void SetMessageAllocatorFor_ActivateServerSession(
        ::grpc::MessageAllocator< ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ActivateServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response) { return this->TerminateServerSession(context, request, response); }));}
    void SetMessageAllocatorFor_TerminateServerSession(
        ::grpc::MessageAllocator< ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TerminateServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response) { return this->ProcessEnding(context, request, response); }));}
    void SetMessageAllocatorFor_ProcessEnding(
        ::grpc::MessageAllocator< ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessEnding(
      ::grpc::CallbackServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ProcessReady<WithCallbackMethod_ActivateServerSession<WithCallbackMethod_TerminateServerSession<WithCallbackMethod_ProcessEnding<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessReady() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessReady() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessReady(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestActivateServerSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTerminateServerSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcessEnding(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessReady() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessReady(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessReady(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ActivateServerSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ActivateServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->TerminateServerSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* TerminateServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ProcessEnding(context, request, response); }));
    }
    ~WithRawCallbackMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ProcessEnding(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessReady : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessReady() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse>* streamer) {
                       return this->StreamedProcessReady(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessReady() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessReady(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessReadyRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessReady(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auxproxyService::ProcessReadyRequest,::auxproxyService::AuxProxyResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ActivateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ActivateServerSession() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse>* streamer) {
                       return this->StreamedActivateServerSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ActivateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ActivateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::ActivateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedActivateServerSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auxproxyService::ActivateServerSessionRequest,::auxproxyService::AuxProxyResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_TerminateServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_TerminateServerSession() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse>* streamer) {
                       return this->StreamedTerminateServerSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_TerminateServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status TerminateServerSession(::grpc::ServerContext* /*context*/, const ::auxproxyService::TerminateServerSessionRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedTerminateServerSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auxproxyService::TerminateServerSessionRequest,::auxproxyService::AuxProxyResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ProcessEnding : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ProcessEnding() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse>* streamer) {
                       return this->StreamedProcessEnding(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ProcessEnding() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ProcessEnding(::grpc::ServerContext* /*context*/, const ::auxproxyService::ProcessEndingRequest* /*request*/, ::auxproxyService::AuxProxyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcessEnding(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::auxproxyService::ProcessEndingRequest,::auxproxyService::AuxProxyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ProcessReady<WithStreamedUnaryMethod_ActivateServerSession<WithStreamedUnaryMethod_TerminateServerSession<WithStreamedUnaryMethod_ProcessEnding<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ProcessReady<WithStreamedUnaryMethod_ActivateServerSession<WithStreamedUnaryMethod_TerminateServerSession<WithStreamedUnaryMethod_ProcessEnding<Service > > > > StreamedService;
};

}  // namespace auxproxyService


#endif  // GRPC_auxproxy_5fgrpc_5fservice_2eproto__INCLUDED
