// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auxproxy_grpc_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_auxproxy_5fgrpc_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_auxproxy_5fgrpc_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_auxproxy_5fgrpc_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_auxproxy_5fgrpc_5fservice_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_auxproxy_5fgrpc_5fservice_2eproto;
namespace auxproxyService {
class ActivateServerSessionRequest;
struct ActivateServerSessionRequestDefaultTypeInternal;
extern ActivateServerSessionRequestDefaultTypeInternal _ActivateServerSessionRequest_default_instance_;
class AuxProxyResponse;
struct AuxProxyResponseDefaultTypeInternal;
extern AuxProxyResponseDefaultTypeInternal _AuxProxyResponse_default_instance_;
class Error;
struct ErrorDefaultTypeInternal;
extern ErrorDefaultTypeInternal _Error_default_instance_;
class ProcessEndingRequest;
struct ProcessEndingRequestDefaultTypeInternal;
extern ProcessEndingRequestDefaultTypeInternal _ProcessEndingRequest_default_instance_;
class ProcessReadyRequest;
struct ProcessReadyRequestDefaultTypeInternal;
extern ProcessReadyRequestDefaultTypeInternal _ProcessReadyRequest_default_instance_;
class TerminateServerSessionRequest;
struct TerminateServerSessionRequestDefaultTypeInternal;
extern TerminateServerSessionRequestDefaultTypeInternal _TerminateServerSessionRequest_default_instance_;
}  // namespace auxproxyService
PROTOBUF_NAMESPACE_OPEN
template<> ::auxproxyService::ActivateServerSessionRequest* Arena::CreateMaybeMessage<::auxproxyService::ActivateServerSessionRequest>(Arena*);
template<> ::auxproxyService::AuxProxyResponse* Arena::CreateMaybeMessage<::auxproxyService::AuxProxyResponse>(Arena*);
template<> ::auxproxyService::Error* Arena::CreateMaybeMessage<::auxproxyService::Error>(Arena*);
template<> ::auxproxyService::ProcessEndingRequest* Arena::CreateMaybeMessage<::auxproxyService::ProcessEndingRequest>(Arena*);
template<> ::auxproxyService::ProcessReadyRequest* Arena::CreateMaybeMessage<::auxproxyService::ProcessReadyRequest>(Arena*);
template<> ::auxproxyService::TerminateServerSessionRequest* Arena::CreateMaybeMessage<::auxproxyService::TerminateServerSessionRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace auxproxyService {

// ===================================================================

class ProcessReadyRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.ProcessReadyRequest) */ {
 public:
  inline ProcessReadyRequest() : ProcessReadyRequest(nullptr) {}
  ~ProcessReadyRequest() override;
  explicit PROTOBUF_CONSTEXPR ProcessReadyRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessReadyRequest(const ProcessReadyRequest& from);
  ProcessReadyRequest(ProcessReadyRequest&& from) noexcept
    : ProcessReadyRequest() {
    *this = ::std::move(from);
  }

  inline ProcessReadyRequest& operator=(const ProcessReadyRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessReadyRequest& operator=(ProcessReadyRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessReadyRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessReadyRequest* internal_default_instance() {
    return reinterpret_cast<const ProcessReadyRequest*>(
               &_ProcessReadyRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProcessReadyRequest& a, ProcessReadyRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessReadyRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessReadyRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessReadyRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessReadyRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessReadyRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessReadyRequest& from) {
    ProcessReadyRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessReadyRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.ProcessReadyRequest";
  }
  protected:
  explicit ProcessReadyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogPathsToUploadFieldNumber = 1,
    kClientPortFieldNumber = 2,
    kGrpcPortFieldNumber = 3,
    kPidFieldNumber = 4,
  };
  // repeated string logPathsToUpload = 1;
  int logpathstoupload_size() const;
  private:
  int _internal_logpathstoupload_size() const;
  public:
  void clear_logpathstoupload();
  const std::string& logpathstoupload(int index) const;
  std::string* mutable_logpathstoupload(int index);
  void set_logpathstoupload(int index, const std::string& value);
  void set_logpathstoupload(int index, std::string&& value);
  void set_logpathstoupload(int index, const char* value);
  void set_logpathstoupload(int index, const char* value, size_t size);
  std::string* add_logpathstoupload();
  void add_logpathstoupload(const std::string& value);
  void add_logpathstoupload(std::string&& value);
  void add_logpathstoupload(const char* value);
  void add_logpathstoupload(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& logpathstoupload() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_logpathstoupload();
  private:
  const std::string& _internal_logpathstoupload(int index) const;
  std::string* _internal_add_logpathstoupload();
  public:

  // int32 clientPort = 2;
  void clear_clientport();
  int32_t clientport() const;
  void set_clientport(int32_t value);
  private:
  int32_t _internal_clientport() const;
  void _internal_set_clientport(int32_t value);
  public:

  // int32 grpcPort = 3;
  void clear_grpcport();
  int32_t grpcport() const;
  void set_grpcport(int32_t value);
  private:
  int32_t _internal_grpcport() const;
  void _internal_set_grpcport(int32_t value);
  public:

  // int32 pid = 4;
  void clear_pid();
  int32_t pid() const;
  void set_pid(int32_t value);
  private:
  int32_t _internal_pid() const;
  void _internal_set_pid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:auxproxyService.ProcessReadyRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> logpathstoupload_;
    int32_t clientport_;
    int32_t grpcport_;
    int32_t pid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class Error final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.Error) */ {
 public:
  inline Error() : Error(nullptr) {}
  ~Error() override;
  explicit PROTOBUF_CONSTEXPR Error(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Error(const Error& from);
  Error(Error&& from) noexcept
    : Error() {
    *this = ::std::move(from);
  }

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline Error& operator=(Error&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Error& default_instance() {
    return *internal_default_instance();
  }
  static inline const Error* internal_default_instance() {
    return reinterpret_cast<const Error*>(
               &_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Error& a, Error& b) {
    a.Swap(&b);
  }
  inline void Swap(Error* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Error* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Error>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Error& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Error& from) {
    Error::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Error* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.Error";
  }
  protected:
  explicit Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorCodeFieldNumber = 1,
    kErrorMsgFieldNumber = 2,
  };
  // string errorCode = 1;
  void clear_errorcode();
  const std::string& errorcode() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errorcode(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errorcode();
  PROTOBUF_NODISCARD std::string* release_errorcode();
  void set_allocated_errorcode(std::string* errorcode);
  private:
  const std::string& _internal_errorcode() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errorcode(const std::string& value);
  std::string* _internal_mutable_errorcode();
  public:

  // string errorMsg = 2;
  void clear_errormsg();
  const std::string& errormsg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_errormsg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_errormsg();
  PROTOBUF_NODISCARD std::string* release_errormsg();
  void set_allocated_errormsg(std::string* errormsg);
  private:
  const std::string& _internal_errormsg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_errormsg(const std::string& value);
  std::string* _internal_mutable_errormsg();
  public:

  // @@protoc_insertion_point(class_scope:auxproxyService.Error)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errorcode_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errormsg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class AuxProxyResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.AuxProxyResponse) */ {
 public:
  inline AuxProxyResponse() : AuxProxyResponse(nullptr) {}
  ~AuxProxyResponse() override;
  explicit PROTOBUF_CONSTEXPR AuxProxyResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  AuxProxyResponse(const AuxProxyResponse& from);
  AuxProxyResponse(AuxProxyResponse&& from) noexcept
    : AuxProxyResponse() {
    *this = ::std::move(from);
  }

  inline AuxProxyResponse& operator=(const AuxProxyResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline AuxProxyResponse& operator=(AuxProxyResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AuxProxyResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const AuxProxyResponse* internal_default_instance() {
    return reinterpret_cast<const AuxProxyResponse*>(
               &_AuxProxyResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(AuxProxyResponse& a, AuxProxyResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(AuxProxyResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AuxProxyResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AuxProxyResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AuxProxyResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const AuxProxyResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const AuxProxyResponse& from) {
    AuxProxyResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AuxProxyResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.AuxProxyResponse";
  }
  protected:
  explicit AuxProxyResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kErrorFieldNumber = 1,
  };
  // .auxproxyService.Error error = 1;
  bool has_error() const;
  private:
  bool _internal_has_error() const;
  public:
  void clear_error();
  const ::auxproxyService::Error& error() const;
  PROTOBUF_NODISCARD ::auxproxyService::Error* release_error();
  ::auxproxyService::Error* mutable_error();
  void set_allocated_error(::auxproxyService::Error* error);
  private:
  const ::auxproxyService::Error& _internal_error() const;
  ::auxproxyService::Error* _internal_mutable_error();
  public:
  void unsafe_arena_set_allocated_error(
      ::auxproxyService::Error* error);
  ::auxproxyService::Error* unsafe_arena_release_error();

  // @@protoc_insertion_point(class_scope:auxproxyService.AuxProxyResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::auxproxyService::Error* error_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ActivateServerSessionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.ActivateServerSessionRequest) */ {
 public:
  inline ActivateServerSessionRequest() : ActivateServerSessionRequest(nullptr) {}
  ~ActivateServerSessionRequest() override;
  explicit PROTOBUF_CONSTEXPR ActivateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActivateServerSessionRequest(const ActivateServerSessionRequest& from);
  ActivateServerSessionRequest(ActivateServerSessionRequest&& from) noexcept
    : ActivateServerSessionRequest() {
    *this = ::std::move(from);
  }

  inline ActivateServerSessionRequest& operator=(const ActivateServerSessionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActivateServerSessionRequest& operator=(ActivateServerSessionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActivateServerSessionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActivateServerSessionRequest* internal_default_instance() {
    return reinterpret_cast<const ActivateServerSessionRequest*>(
               &_ActivateServerSessionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ActivateServerSessionRequest& a, ActivateServerSessionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ActivateServerSessionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActivateServerSessionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActivateServerSessionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActivateServerSessionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActivateServerSessionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ActivateServerSessionRequest& from) {
    ActivateServerSessionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActivateServerSessionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.ActivateServerSessionRequest";
  }
  protected:
  explicit ActivateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerSessionIdFieldNumber = 1,
    kMaxClientsFieldNumber = 2,
  };
  // string serverSessionId = 1;
  void clear_serversessionid();
  const std::string& serversessionid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serversessionid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serversessionid();
  PROTOBUF_NODISCARD std::string* release_serversessionid();
  void set_allocated_serversessionid(std::string* serversessionid);
  private:
  const std::string& _internal_serversessionid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serversessionid(const std::string& value);
  std::string* _internal_mutable_serversessionid();
  public:

  // int32 maxClients = 2;
  void clear_maxclients();
  int32_t maxclients() const;
  void set_maxclients(int32_t value);
  private:
  int32_t _internal_maxclients() const;
  void _internal_set_maxclients(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:auxproxyService.ActivateServerSessionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serversessionid_;
    int32_t maxclients_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class TerminateServerSessionRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.TerminateServerSessionRequest) */ {
 public:
  inline TerminateServerSessionRequest() : TerminateServerSessionRequest(nullptr) {}
  ~TerminateServerSessionRequest() override;
  explicit PROTOBUF_CONSTEXPR TerminateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TerminateServerSessionRequest(const TerminateServerSessionRequest& from);
  TerminateServerSessionRequest(TerminateServerSessionRequest&& from) noexcept
    : TerminateServerSessionRequest() {
    *this = ::std::move(from);
  }

  inline TerminateServerSessionRequest& operator=(const TerminateServerSessionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline TerminateServerSessionRequest& operator=(TerminateServerSessionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TerminateServerSessionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const TerminateServerSessionRequest* internal_default_instance() {
    return reinterpret_cast<const TerminateServerSessionRequest*>(
               &_TerminateServerSessionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TerminateServerSessionRequest& a, TerminateServerSessionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(TerminateServerSessionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TerminateServerSessionRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TerminateServerSessionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TerminateServerSessionRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TerminateServerSessionRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TerminateServerSessionRequest& from) {
    TerminateServerSessionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TerminateServerSessionRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.TerminateServerSessionRequest";
  }
  protected:
  explicit TerminateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kServerSessionIdFieldNumber = 1,
  };
  // string serverSessionId = 1;
  void clear_serversessionid();
  const std::string& serversessionid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_serversessionid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_serversessionid();
  PROTOBUF_NODISCARD std::string* release_serversessionid();
  void set_allocated_serversessionid(std::string* serversessionid);
  private:
  const std::string& _internal_serversessionid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_serversessionid(const std::string& value);
  std::string* _internal_mutable_serversessionid();
  public:

  // @@protoc_insertion_point(class_scope:auxproxyService.TerminateServerSessionRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr serversessionid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ProcessEndingRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:auxproxyService.ProcessEndingRequest) */ {
 public:
  inline ProcessEndingRequest() : ProcessEndingRequest(nullptr) {}
  ~ProcessEndingRequest() override;
  explicit PROTOBUF_CONSTEXPR ProcessEndingRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessEndingRequest(const ProcessEndingRequest& from);
  ProcessEndingRequest(ProcessEndingRequest&& from) noexcept
    : ProcessEndingRequest() {
    *this = ::std::move(from);
  }

  inline ProcessEndingRequest& operator=(const ProcessEndingRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessEndingRequest& operator=(ProcessEndingRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessEndingRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessEndingRequest* internal_default_instance() {
    return reinterpret_cast<const ProcessEndingRequest*>(
               &_ProcessEndingRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ProcessEndingRequest& a, ProcessEndingRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessEndingRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessEndingRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessEndingRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessEndingRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessEndingRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessEndingRequest& from) {
    ProcessEndingRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessEndingRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "auxproxyService.ProcessEndingRequest";
  }
  protected:
  explicit ProcessEndingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPidFieldNumber = 1,
  };
  // int32 pid = 1;
  void clear_pid();
  int32_t pid() const;
  void set_pid(int32_t value);
  private:
  int32_t _internal_pid() const;
  void _internal_set_pid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:auxproxyService.ProcessEndingRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t pid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_auxproxy_5fgrpc_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProcessReadyRequest

// repeated string logPathsToUpload = 1;
inline int ProcessReadyRequest::_internal_logpathstoupload_size() const {
  return _impl_.logpathstoupload_.size();
}
inline int ProcessReadyRequest::logpathstoupload_size() const {
  return _internal_logpathstoupload_size();
}
inline void ProcessReadyRequest::clear_logpathstoupload() {
  _impl_.logpathstoupload_.Clear();
}
inline std::string* ProcessReadyRequest::add_logpathstoupload() {
  std::string* _s = _internal_add_logpathstoupload();
  // @@protoc_insertion_point(field_add_mutable:auxproxyService.ProcessReadyRequest.logPathsToUpload)
  return _s;
}
inline const std::string& ProcessReadyRequest::_internal_logpathstoupload(int index) const {
  return _impl_.logpathstoupload_.Get(index);
}
inline const std::string& ProcessReadyRequest::logpathstoupload(int index) const {
  // @@protoc_insertion_point(field_get:auxproxyService.ProcessReadyRequest.logPathsToUpload)
  return _internal_logpathstoupload(index);
}
inline std::string* ProcessReadyRequest::mutable_logpathstoupload(int index) {
  // @@protoc_insertion_point(field_mutable:auxproxyService.ProcessReadyRequest.logPathsToUpload)
  return _impl_.logpathstoupload_.Mutable(index);
}
inline void ProcessReadyRequest::set_logpathstoupload(int index, const std::string& value) {
  _impl_.logpathstoupload_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::set_logpathstoupload(int index, std::string&& value) {
  _impl_.logpathstoupload_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::set_logpathstoupload(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.logpathstoupload_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::set_logpathstoupload(int index, const char* value, size_t size) {
  _impl_.logpathstoupload_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline std::string* ProcessReadyRequest::_internal_add_logpathstoupload() {
  return _impl_.logpathstoupload_.Add();
}
inline void ProcessReadyRequest::add_logpathstoupload(const std::string& value) {
  _impl_.logpathstoupload_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::add_logpathstoupload(std::string&& value) {
  _impl_.logpathstoupload_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::add_logpathstoupload(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.logpathstoupload_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline void ProcessReadyRequest::add_logpathstoupload(const char* value, size_t size) {
  _impl_.logpathstoupload_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:auxproxyService.ProcessReadyRequest.logPathsToUpload)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ProcessReadyRequest::logpathstoupload() const {
  // @@protoc_insertion_point(field_list:auxproxyService.ProcessReadyRequest.logPathsToUpload)
  return _impl_.logpathstoupload_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ProcessReadyRequest::mutable_logpathstoupload() {
  // @@protoc_insertion_point(field_mutable_list:auxproxyService.ProcessReadyRequest.logPathsToUpload)
  return &_impl_.logpathstoupload_;
}

// int32 clientPort = 2;
inline void ProcessReadyRequest::clear_clientport() {
  _impl_.clientport_ = 0;
}
inline int32_t ProcessReadyRequest::_internal_clientport() const {
  return _impl_.clientport_;
}
inline int32_t ProcessReadyRequest::clientport() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ProcessReadyRequest.clientPort)
  return _internal_clientport();
}
inline void ProcessReadyRequest::_internal_set_clientport(int32_t value) {
  
  _impl_.clientport_ = value;
}
inline void ProcessReadyRequest::set_clientport(int32_t value) {
  _internal_set_clientport(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessReadyRequest.clientPort)
}

// int32 grpcPort = 3;
inline void ProcessReadyRequest::clear_grpcport() {
  _impl_.grpcport_ = 0;
}
inline int32_t ProcessReadyRequest::_internal_grpcport() const {
  return _impl_.grpcport_;
}
inline int32_t ProcessReadyRequest::grpcport() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ProcessReadyRequest.grpcPort)
  return _internal_grpcport();
}
inline void ProcessReadyRequest::_internal_set_grpcport(int32_t value) {
  
  _impl_.grpcport_ = value;
}
inline void ProcessReadyRequest::set_grpcport(int32_t value) {
  _internal_set_grpcport(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessReadyRequest.grpcPort)
}

// int32 pid = 4;
inline void ProcessReadyRequest::clear_pid() {
  _impl_.pid_ = 0;
}
inline int32_t ProcessReadyRequest::_internal_pid() const {
  return _impl_.pid_;
}
inline int32_t ProcessReadyRequest::pid() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ProcessReadyRequest.pid)
  return _internal_pid();
}
inline void ProcessReadyRequest::_internal_set_pid(int32_t value) {
  
  _impl_.pid_ = value;
}
inline void ProcessReadyRequest::set_pid(int32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessReadyRequest.pid)
}

// -------------------------------------------------------------------

// Error

// string errorCode = 1;
inline void Error::clear_errorcode() {
  _impl_.errorcode_.ClearToEmpty();
}
inline const std::string& Error::errorcode() const {
  // @@protoc_insertion_point(field_get:auxproxyService.Error.errorCode)
  return _internal_errorcode();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_errorcode(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errorcode_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:auxproxyService.Error.errorCode)
}
inline std::string* Error::mutable_errorcode() {
  std::string* _s = _internal_mutable_errorcode();
  // @@protoc_insertion_point(field_mutable:auxproxyService.Error.errorCode)
  return _s;
}
inline const std::string& Error::_internal_errorcode() const {
  return _impl_.errorcode_.Get();
}
inline void Error::_internal_set_errorcode(const std::string& value) {
  
  _impl_.errorcode_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_errorcode() {
  
  return _impl_.errorcode_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_errorcode() {
  // @@protoc_insertion_point(field_release:auxproxyService.Error.errorCode)
  return _impl_.errorcode_.Release();
}
inline void Error::set_allocated_errorcode(std::string* errorcode) {
  if (errorcode != nullptr) {
    
  } else {
    
  }
  _impl_.errorcode_.SetAllocated(errorcode, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errorcode_.IsDefault()) {
    _impl_.errorcode_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:auxproxyService.Error.errorCode)
}

// string errorMsg = 2;
inline void Error::clear_errormsg() {
  _impl_.errormsg_.ClearToEmpty();
}
inline const std::string& Error::errormsg() const {
  // @@protoc_insertion_point(field_get:auxproxyService.Error.errorMsg)
  return _internal_errormsg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_errormsg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.errormsg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:auxproxyService.Error.errorMsg)
}
inline std::string* Error::mutable_errormsg() {
  std::string* _s = _internal_mutable_errormsg();
  // @@protoc_insertion_point(field_mutable:auxproxyService.Error.errorMsg)
  return _s;
}
inline const std::string& Error::_internal_errormsg() const {
  return _impl_.errormsg_.Get();
}
inline void Error::_internal_set_errormsg(const std::string& value) {
  
  _impl_.errormsg_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_errormsg() {
  
  return _impl_.errormsg_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_errormsg() {
  // @@protoc_insertion_point(field_release:auxproxyService.Error.errorMsg)
  return _impl_.errormsg_.Release();
}
inline void Error::set_allocated_errormsg(std::string* errormsg) {
  if (errormsg != nullptr) {
    
  } else {
    
  }
  _impl_.errormsg_.SetAllocated(errormsg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.errormsg_.IsDefault()) {
    _impl_.errormsg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:auxproxyService.Error.errorMsg)
}

// -------------------------------------------------------------------

// AuxProxyResponse

// .auxproxyService.Error error = 1;
inline bool AuxProxyResponse::_internal_has_error() const {
  return this != internal_default_instance() && _impl_.error_ != nullptr;
}
inline bool AuxProxyResponse::has_error() const {
  return _internal_has_error();
}
inline void AuxProxyResponse::clear_error() {
  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
}
inline const ::auxproxyService::Error& AuxProxyResponse::_internal_error() const {
  const ::auxproxyService::Error* p = _impl_.error_;
  return p != nullptr ? *p : reinterpret_cast<const ::auxproxyService::Error&>(
      ::auxproxyService::_Error_default_instance_);
}
inline const ::auxproxyService::Error& AuxProxyResponse::error() const {
  // @@protoc_insertion_point(field_get:auxproxyService.AuxProxyResponse.error)
  return _internal_error();
}
inline void AuxProxyResponse::unsafe_arena_set_allocated_error(
    ::auxproxyService::Error* error) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.error_);
  }
  _impl_.error_ = error;
  if (error) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:auxproxyService.AuxProxyResponse.error)
}
inline ::auxproxyService::Error* AuxProxyResponse::release_error() {
  
  ::auxproxyService::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::auxproxyService::Error* AuxProxyResponse::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_release:auxproxyService.AuxProxyResponse.error)
  
  ::auxproxyService::Error* temp = _impl_.error_;
  _impl_.error_ = nullptr;
  return temp;
}
inline ::auxproxyService::Error* AuxProxyResponse::_internal_mutable_error() {
  
  if (_impl_.error_ == nullptr) {
    auto* p = CreateMaybeMessage<::auxproxyService::Error>(GetArenaForAllocation());
    _impl_.error_ = p;
  }
  return _impl_.error_;
}
inline ::auxproxyService::Error* AuxProxyResponse::mutable_error() {
  ::auxproxyService::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:auxproxyService.AuxProxyResponse.error)
  return _msg;
}
inline void AuxProxyResponse::set_allocated_error(::auxproxyService::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.error_;
  }
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(error);
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.error_ = error;
  // @@protoc_insertion_point(field_set_allocated:auxproxyService.AuxProxyResponse.error)
}

// -------------------------------------------------------------------

// ActivateServerSessionRequest

// string serverSessionId = 1;
inline void ActivateServerSessionRequest::clear_serversessionid() {
  _impl_.serversessionid_.ClearToEmpty();
}
inline const std::string& ActivateServerSessionRequest::serversessionid() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ActivateServerSessionRequest.serverSessionId)
  return _internal_serversessionid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ActivateServerSessionRequest::set_serversessionid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.serversessionid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:auxproxyService.ActivateServerSessionRequest.serverSessionId)
}
inline std::string* ActivateServerSessionRequest::mutable_serversessionid() {
  std::string* _s = _internal_mutable_serversessionid();
  // @@protoc_insertion_point(field_mutable:auxproxyService.ActivateServerSessionRequest.serverSessionId)
  return _s;
}
inline const std::string& ActivateServerSessionRequest::_internal_serversessionid() const {
  return _impl_.serversessionid_.Get();
}
inline void ActivateServerSessionRequest::_internal_set_serversessionid(const std::string& value) {
  
  _impl_.serversessionid_.Set(value, GetArenaForAllocation());
}
inline std::string* ActivateServerSessionRequest::_internal_mutable_serversessionid() {
  
  return _impl_.serversessionid_.Mutable(GetArenaForAllocation());
}
inline std::string* ActivateServerSessionRequest::release_serversessionid() {
  // @@protoc_insertion_point(field_release:auxproxyService.ActivateServerSessionRequest.serverSessionId)
  return _impl_.serversessionid_.Release();
}
inline void ActivateServerSessionRequest::set_allocated_serversessionid(std::string* serversessionid) {
  if (serversessionid != nullptr) {
    
  } else {
    
  }
  _impl_.serversessionid_.SetAllocated(serversessionid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.serversessionid_.IsDefault()) {
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:auxproxyService.ActivateServerSessionRequest.serverSessionId)
}

// int32 maxClients = 2;
inline void ActivateServerSessionRequest::clear_maxclients() {
  _impl_.maxclients_ = 0;
}
inline int32_t ActivateServerSessionRequest::_internal_maxclients() const {
  return _impl_.maxclients_;
}
inline int32_t ActivateServerSessionRequest::maxclients() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ActivateServerSessionRequest.maxClients)
  return _internal_maxclients();
}
inline void ActivateServerSessionRequest::_internal_set_maxclients(int32_t value) {
  
  _impl_.maxclients_ = value;
}
inline void ActivateServerSessionRequest::set_maxclients(int32_t value) {
  _internal_set_maxclients(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ActivateServerSessionRequest.maxClients)
}

// -------------------------------------------------------------------

// TerminateServerSessionRequest

// string serverSessionId = 1;
inline void TerminateServerSessionRequest::clear_serversessionid() {
  _impl_.serversessionid_.ClearToEmpty();
}
inline const std::string& TerminateServerSessionRequest::serversessionid() const {
  // @@protoc_insertion_point(field_get:auxproxyService.TerminateServerSessionRequest.serverSessionId)
  return _internal_serversessionid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TerminateServerSessionRequest::set_serversessionid(ArgT0&& arg0, ArgT... args) {
 
 _impl_.serversessionid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:auxproxyService.TerminateServerSessionRequest.serverSessionId)
}
inline std::string* TerminateServerSessionRequest::mutable_serversessionid() {
  std::string* _s = _internal_mutable_serversessionid();
  // @@protoc_insertion_point(field_mutable:auxproxyService.TerminateServerSessionRequest.serverSessionId)
  return _s;
}
inline const std::string& TerminateServerSessionRequest::_internal_serversessionid() const {
  return _impl_.serversessionid_.Get();
}
inline void TerminateServerSessionRequest::_internal_set_serversessionid(const std::string& value) {
  
  _impl_.serversessionid_.Set(value, GetArenaForAllocation());
}
inline std::string* TerminateServerSessionRequest::_internal_mutable_serversessionid() {
  
  return _impl_.serversessionid_.Mutable(GetArenaForAllocation());
}
inline std::string* TerminateServerSessionRequest::release_serversessionid() {
  // @@protoc_insertion_point(field_release:auxproxyService.TerminateServerSessionRequest.serverSessionId)
  return _impl_.serversessionid_.Release();
}
inline void TerminateServerSessionRequest::set_allocated_serversessionid(std::string* serversessionid) {
  if (serversessionid != nullptr) {
    
  } else {
    
  }
  _impl_.serversessionid_.SetAllocated(serversessionid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.serversessionid_.IsDefault()) {
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:auxproxyService.TerminateServerSessionRequest.serverSessionId)
}

// -------------------------------------------------------------------

// ProcessEndingRequest

// int32 pid = 1;
inline void ProcessEndingRequest::clear_pid() {
  _impl_.pid_ = 0;
}
inline int32_t ProcessEndingRequest::_internal_pid() const {
  return _impl_.pid_;
}
inline int32_t ProcessEndingRequest::pid() const {
  // @@protoc_insertion_point(field_get:auxproxyService.ProcessEndingRequest.pid)
  return _internal_pid();
}
inline void ProcessEndingRequest::_internal_set_pid(int32_t value) {
  
  _impl_.pid_ = value;
}
inline void ProcessEndingRequest::set_pid(int32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:auxproxyService.ProcessEndingRequest.pid)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace auxproxyService

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_auxproxy_5fgrpc_5fservice_2eproto
