// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: process_grpc_service.proto
#ifndef GRPC_process_5fgrpc_5fservice_2eproto__INCLUDED
#define GRPC_process_5fgrpc_5fservice_2eproto__INCLUDED

#include "process_grpc_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace processService {

class ProcessGrpcSdkService final {
 public:
  static constexpr char const* service_full_name() {
    return "processService.ProcessGrpcSdkService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::processService::HealthCheckResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>> AsyncOnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>>(AsyncOnHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>> PrepareAsyncOnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>>(PrepareAsyncOnHealthCheckRaw(context, request, cq));
    }
    virtual ::grpc::Status OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::processService::ProcessResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>> AsyncOnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>>(AsyncOnStartServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>> PrepareAsyncOnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>>(PrepareAsyncOnStartServerSessionRaw(context, request, cq));
    }
    virtual ::grpc::Status OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::processService::ProcessResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>> AsyncOnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>>(AsyncOnProcessTerminateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>> PrepareAsyncOnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>>(PrepareAsyncOnProcessTerminateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>* AsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::HealthCheckResponse>* PrepareAsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>* AsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>* PrepareAsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>* AsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::processService::ProcessResponse>* PrepareAsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::processService::HealthCheckResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>> AsyncOnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>>(AsyncOnHealthCheckRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>> PrepareAsyncOnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>>(PrepareAsyncOnHealthCheckRaw(context, request, cq));
    }
    ::grpc::Status OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::processService::ProcessResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>> AsyncOnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>>(AsyncOnStartServerSessionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>> PrepareAsyncOnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>>(PrepareAsyncOnStartServerSessionRaw(context, request, cq));
    }
    ::grpc::Status OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::processService::ProcessResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>> AsyncOnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>>(AsyncOnProcessTerminateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>> PrepareAsyncOnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>>(PrepareAsyncOnProcessTerminateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, std::function<void(::grpc::Status)>) override;
      void OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)>) override;
      void OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)>) override;
      void OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>* AsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>* PrepareAsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* AsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* PrepareAsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* AsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* PrepareAsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_OnHealthCheck_;
    const ::grpc::internal::RpcMethod rpcmethod_OnStartServerSession_;
    const ::grpc::internal::RpcMethod rpcmethod_OnProcessTerminate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status OnHealthCheck(::grpc::ServerContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response);
    virtual ::grpc::Status OnStartServerSession(::grpc::ServerContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response);
    virtual ::grpc::Status OnProcessTerminate(::grpc::ServerContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHealthCheck(::grpc::ServerContext* context, ::processService::HealthCheckRequest* request, ::grpc::ServerAsyncResponseWriter< ::processService::HealthCheckResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnStartServerSession(::grpc::ServerContext* context, ::processService::StartServerSessionRequest* request, ::grpc::ServerAsyncResponseWriter< ::processService::ProcessResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnProcessTerminate(::grpc::ServerContext* context, ::processService::ProcessTerminateRequest* request, ::grpc::ServerAsyncResponseWriter< ::processService::ProcessResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_OnHealthCheck<WithAsyncMethod_OnStartServerSession<WithAsyncMethod_OnProcessTerminate<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::processService::HealthCheckRequest, ::processService::HealthCheckResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response) { return this->OnHealthCheck(context, request, response); }));}
    void SetMessageAllocatorFor_OnHealthCheck(
        ::grpc::MessageAllocator< ::processService::HealthCheckRequest, ::processService::HealthCheckResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::processService::HealthCheckRequest, ::processService::HealthCheckResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnHealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::processService::StartServerSessionRequest, ::processService::ProcessResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response) { return this->OnStartServerSession(context, request, response); }));}
    void SetMessageAllocatorFor_OnStartServerSession(
        ::grpc::MessageAllocator< ::processService::StartServerSessionRequest, ::processService::ProcessResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::processService::StartServerSessionRequest, ::processService::ProcessResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnStartServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::processService::ProcessTerminateRequest, ::processService::ProcessResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response) { return this->OnProcessTerminate(context, request, response); }));}
    void SetMessageAllocatorFor_OnProcessTerminate(
        ::grpc::MessageAllocator< ::processService::ProcessTerminateRequest, ::processService::ProcessResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::processService::ProcessTerminateRequest, ::processService::ProcessResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnProcessTerminate(
      ::grpc::CallbackServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_OnHealthCheck<WithCallbackMethod_OnStartServerSession<WithCallbackMethod_OnProcessTerminate<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnHealthCheck(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnStartServerSession(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestOnProcessTerminate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnHealthCheck(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnHealthCheck(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnStartServerSession(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnStartServerSession(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->OnProcessTerminate(context, request, response); }));
    }
    ~WithRawCallbackMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* OnProcessTerminate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnHealthCheck : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnHealthCheck() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::processService::HealthCheckRequest, ::processService::HealthCheckResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::processService::HealthCheckRequest, ::processService::HealthCheckResponse>* streamer) {
                       return this->StreamedOnHealthCheck(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnHealthCheck() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnHealthCheck(::grpc::ServerContext* /*context*/, const ::processService::HealthCheckRequest* /*request*/, ::processService::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnHealthCheck(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::processService::HealthCheckRequest,::processService::HealthCheckResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnStartServerSession : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnStartServerSession() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::processService::StartServerSessionRequest, ::processService::ProcessResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::processService::StartServerSessionRequest, ::processService::ProcessResponse>* streamer) {
                       return this->StreamedOnStartServerSession(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnStartServerSession() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnStartServerSession(::grpc::ServerContext* /*context*/, const ::processService::StartServerSessionRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnStartServerSession(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::processService::StartServerSessionRequest,::processService::ProcessResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_OnProcessTerminate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_OnProcessTerminate() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::processService::ProcessTerminateRequest, ::processService::ProcessResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::processService::ProcessTerminateRequest, ::processService::ProcessResponse>* streamer) {
                       return this->StreamedOnProcessTerminate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_OnProcessTerminate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status OnProcessTerminate(::grpc::ServerContext* /*context*/, const ::processService::ProcessTerminateRequest* /*request*/, ::processService::ProcessResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedOnProcessTerminate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::processService::ProcessTerminateRequest,::processService::ProcessResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_OnHealthCheck<WithStreamedUnaryMethod_OnStartServerSession<WithStreamedUnaryMethod_OnProcessTerminate<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_OnHealthCheck<WithStreamedUnaryMethod_OnStartServerSession<WithStreamedUnaryMethod_OnProcessTerminate<Service > > > StreamedService;
};

}  // namespace processService


#endif  // GRPC_process_5fgrpc_5fservice_2eproto__INCLUDED
