// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: process_grpc_service.proto

#include "process_grpc_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace processService {
PROTOBUF_CONSTEXPR HealthCheckRequest::HealthCheckRequest(
    ::_pbi::ConstantInitialized) {}
struct HealthCheckRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckRequestDefaultTypeInternal() {}
  union {
    HealthCheckRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckRequestDefaultTypeInternal _HealthCheckRequest_default_instance_;
PROTOBUF_CONSTEXPR HealthCheckResponse::HealthCheckResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.healthstatus_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HealthCheckResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HealthCheckResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HealthCheckResponseDefaultTypeInternal() {}
  union {
    HealthCheckResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HealthCheckResponseDefaultTypeInternal _HealthCheckResponse_default_instance_;
PROTOBUF_CONSTEXPR SessionProperty::SessionProperty(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SessionPropertyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SessionPropertyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SessionPropertyDefaultTypeInternal() {}
  union {
    SessionProperty _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SessionPropertyDefaultTypeInternal _SessionProperty_default_instance_;
PROTOBUF_CONSTEXPR ServerSession::ServerSession(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.sessionproperties_)*/{}
  , /*decltype(_impl_.serversessionid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.fleetid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.ipaddress_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sessiondata_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.maxclients_)*/0
  , /*decltype(_impl_.joinable_)*/false
  , /*decltype(_impl_.port_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ServerSessionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerSessionDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerSessionDefaultTypeInternal() {}
  union {
    ServerSession _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerSessionDefaultTypeInternal _ServerSession_default_instance_;
PROTOBUF_CONSTEXPR StartServerSessionRequest::StartServerSessionRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.serversession_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct StartServerSessionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR StartServerSessionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartServerSessionRequestDefaultTypeInternal() {}
  union {
    StartServerSessionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartServerSessionRequestDefaultTypeInternal _StartServerSessionRequest_default_instance_;
PROTOBUF_CONSTEXPR ProcessTerminateRequest::ProcessTerminateRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.terminationtime_)*/int64_t{0}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProcessTerminateRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessTerminateRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessTerminateRequestDefaultTypeInternal() {}
  union {
    ProcessTerminateRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessTerminateRequestDefaultTypeInternal _ProcessTerminateRequest_default_instance_;
PROTOBUF_CONSTEXPR ProcessResponse::ProcessResponse(
    ::_pbi::ConstantInitialized) {}
struct ProcessResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessResponseDefaultTypeInternal() {}
  union {
    ProcessResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessResponseDefaultTypeInternal _ProcessResponse_default_instance_;
}  // namespace processService
static ::_pb::Metadata file_level_metadata_process_5fgrpc_5fservice_2eproto[7];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_process_5fgrpc_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_process_5fgrpc_5fservice_2eproto = nullptr;

const uint32_t TableStruct_process_5fgrpc_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::HealthCheckRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::HealthCheckResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::processService::HealthCheckResponse, _impl_.healthstatus_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::SessionProperty, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::processService::SessionProperty, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::processService::SessionProperty, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.serversessionid_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.fleetid_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.maxclients_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.joinable_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.sessionproperties_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.port_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.ipaddress_),
  PROTOBUF_FIELD_OFFSET(::processService::ServerSession, _impl_.sessiondata_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::StartServerSessionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::processService::StartServerSessionRequest, _impl_.serversession_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::ProcessTerminateRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::processService::ProcessTerminateRequest, _impl_.terminationtime_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::processService::ProcessResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::processService::HealthCheckRequest)},
  { 6, -1, -1, sizeof(::processService::HealthCheckResponse)},
  { 13, -1, -1, sizeof(::processService::SessionProperty)},
  { 21, -1, -1, sizeof(::processService::ServerSession)},
  { 36, -1, -1, sizeof(::processService::StartServerSessionRequest)},
  { 43, -1, -1, sizeof(::processService::ProcessTerminateRequest)},
  { 50, -1, -1, sizeof(::processService::ProcessResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::processService::_HealthCheckRequest_default_instance_._instance,
  &::processService::_HealthCheckResponse_default_instance_._instance,
  &::processService::_SessionProperty_default_instance_._instance,
  &::processService::_ServerSession_default_instance_._instance,
  &::processService::_StartServerSessionRequest_default_instance_._instance,
  &::processService::_ProcessTerminateRequest_default_instance_._instance,
  &::processService::_ProcessResponse_default_instance_._instance,
};

const char descriptor_table_protodef_process_5fgrpc_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032process_grpc_service.proto\022\016processSer"
  "vice\"\024\n\022HealthCheckRequest\"+\n\023HealthChec"
  "kResponse\022\024\n\014healthStatus\030\001 \001(\010\"-\n\017Sessi"
  "onProperty\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\337"
  "\001\n\rServerSession\022\027\n\017serverSessionId\030\001 \001("
  "\t\022\017\n\007fleetId\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\022\n\nmaxC"
  "lients\030\004 \001(\005\022\020\n\010joinable\030\005 \001(\010\022:\n\021sessio"
  "nProperties\030\006 \003(\0132\037.processService.Sessi"
  "onProperty\022\014\n\004port\030\007 \001(\005\022\021\n\tipAddress\030\010 "
  "\001(\t\022\023\n\013sessionData\030\t \001(\t\"Q\n\031StartServerS"
  "essionRequest\0224\n\rserverSession\030\001 \001(\0132\035.p"
  "rocessService.ServerSession\"2\n\027ProcessTe"
  "rminateRequest\022\027\n\017terminationTime\030\001 \001(\003\""
  "\021\n\017ProcessResponse2\273\002\n\025ProcessGrpcSdkSer"
  "vice\022Z\n\rOnHealthCheck\022\".processService.H"
  "ealthCheckRequest\032#.processService.Healt"
  "hCheckResponse\"\000\022d\n\024OnStartServerSession"
  "\022).processService.StartServerSessionRequ"
  "est\032\037.processService.ProcessResponse\"\000\022`"
  "\n\022OnProcessTerminate\022\'.processService.Pr"
  "ocessTerminateRequest\032\037.processService.P"
  "rocessResponse\"\000BM\n\037io.grpc.examples.pro"
  "cessServiceB\023processServiceProtoP\001\242\002\022Pro"
  "cessGrpcServiceb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_process_5fgrpc_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_process_5fgrpc_5fservice_2eproto = {
    false, false, 943, descriptor_table_protodef_process_5fgrpc_5fservice_2eproto,
    "process_grpc_service.proto",
    &descriptor_table_process_5fgrpc_5fservice_2eproto_once, nullptr, 0, 7,
    schemas, file_default_instances, TableStruct_process_5fgrpc_5fservice_2eproto::offsets,
    file_level_metadata_process_5fgrpc_5fservice_2eproto, file_level_enum_descriptors_process_5fgrpc_5fservice_2eproto,
    file_level_service_descriptors_process_5fgrpc_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_process_5fgrpc_5fservice_2eproto_getter() {
  return &descriptor_table_process_5fgrpc_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_process_5fgrpc_5fservice_2eproto(&descriptor_table_process_5fgrpc_5fservice_2eproto);
namespace processService {

// ===================================================================

class HealthCheckRequest::_Internal {
 public:
};

HealthCheckRequest::HealthCheckRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:processService.HealthCheckRequest)
}
HealthCheckRequest::HealthCheckRequest(const HealthCheckRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HealthCheckRequest* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:processService.HealthCheckRequest)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthCheckRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthCheckRequest::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HealthCheckRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[0]);
}

// ===================================================================

class HealthCheckResponse::_Internal {
 public:
};

HealthCheckResponse::HealthCheckResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:processService.HealthCheckResponse)
}
HealthCheckResponse::HealthCheckResponse(const HealthCheckResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HealthCheckResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.healthstatus_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.healthstatus_ = from._impl_.healthstatus_;
  // @@protoc_insertion_point(copy_constructor:processService.HealthCheckResponse)
}

inline void HealthCheckResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.healthstatus_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HealthCheckResponse::~HealthCheckResponse() {
  // @@protoc_insertion_point(destructor:processService.HealthCheckResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HealthCheckResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void HealthCheckResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HealthCheckResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:processService.HealthCheckResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.healthstatus_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HealthCheckResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool healthStatus = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.healthstatus_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HealthCheckResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:processService.HealthCheckResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool healthStatus = 1;
  if (this->_internal_healthstatus() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(1, this->_internal_healthstatus(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:processService.HealthCheckResponse)
  return target;
}

size_t HealthCheckResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:processService.HealthCheckResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool healthStatus = 1;
  if (this->_internal_healthstatus() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HealthCheckResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HealthCheckResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HealthCheckResponse::GetClassData() const { return &_class_data_; }


void HealthCheckResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HealthCheckResponse*>(&to_msg);
  auto& from = static_cast<const HealthCheckResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:processService.HealthCheckResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_healthstatus() != 0) {
    _this->_internal_set_healthstatus(from._internal_healthstatus());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HealthCheckResponse::CopyFrom(const HealthCheckResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:processService.HealthCheckResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HealthCheckResponse::IsInitialized() const {
  return true;
}

void HealthCheckResponse::InternalSwap(HealthCheckResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.healthstatus_, other->_impl_.healthstatus_);
}

::PROTOBUF_NAMESPACE_ID::Metadata HealthCheckResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[1]);
}

// ===================================================================

class SessionProperty::_Internal {
 public:
};

SessionProperty::SessionProperty(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:processService.SessionProperty)
}
SessionProperty::SessionProperty(const SessionProperty& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SessionProperty* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:processService.SessionProperty)
}

inline void SessionProperty::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SessionProperty::~SessionProperty() {
  // @@protoc_insertion_point(destructor:processService.SessionProperty)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SessionProperty::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
}

void SessionProperty::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SessionProperty::Clear() {
// @@protoc_insertion_point(message_clear_start:processService.SessionProperty)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SessionProperty::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.SessionProperty.key"));
        } else
          goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.SessionProperty.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SessionProperty::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:processService.SessionProperty)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.SessionProperty.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.SessionProperty.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:processService.SessionProperty)
  return target;
}

size_t SessionProperty::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:processService.SessionProperty)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SessionProperty::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SessionProperty::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SessionProperty::GetClassData() const { return &_class_data_; }


void SessionProperty::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SessionProperty*>(&to_msg);
  auto& from = static_cast<const SessionProperty&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:processService.SessionProperty)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SessionProperty::CopyFrom(const SessionProperty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:processService.SessionProperty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionProperty::IsInitialized() const {
  return true;
}

void SessionProperty::InternalSwap(SessionProperty* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata SessionProperty::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[2]);
}

// ===================================================================

class ServerSession::_Internal {
 public:
};

ServerSession::ServerSession(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:processService.ServerSession)
}
ServerSession::ServerSession(const ServerSession& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ServerSession* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.sessionproperties_){from._impl_.sessionproperties_}
    , decltype(_impl_.serversessionid_){}
    , decltype(_impl_.fleetid_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.ipaddress_){}
    , decltype(_impl_.sessiondata_){}
    , decltype(_impl_.maxclients_){}
    , decltype(_impl_.joinable_){}
    , decltype(_impl_.port_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_serversessionid().empty()) {
    _this->_impl_.serversessionid_.Set(from._internal_serversessionid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.fleetid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fleetid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_fleetid().empty()) {
    _this->_impl_.fleetid_.Set(from._internal_fleetid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.ipaddress_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipaddress_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_ipaddress().empty()) {
    _this->_impl_.ipaddress_.Set(from._internal_ipaddress(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sessiondata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sessiondata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sessiondata().empty()) {
    _this->_impl_.sessiondata_.Set(from._internal_sessiondata(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.maxclients_, &from._impl_.maxclients_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.port_) -
    reinterpret_cast<char*>(&_impl_.maxclients_)) + sizeof(_impl_.port_));
  // @@protoc_insertion_point(copy_constructor:processService.ServerSession)
}

inline void ServerSession::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.sessionproperties_){arena}
    , decltype(_impl_.serversessionid_){}
    , decltype(_impl_.fleetid_){}
    , decltype(_impl_.name_){}
    , decltype(_impl_.ipaddress_){}
    , decltype(_impl_.sessiondata_){}
    , decltype(_impl_.maxclients_){0}
    , decltype(_impl_.joinable_){false}
    , decltype(_impl_.port_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.fleetid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.fleetid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.ipaddress_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ipaddress_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sessiondata_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sessiondata_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ServerSession::~ServerSession() {
  // @@protoc_insertion_point(destructor:processService.ServerSession)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ServerSession::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.sessionproperties_.~RepeatedPtrField();
  _impl_.serversessionid_.Destroy();
  _impl_.fleetid_.Destroy();
  _impl_.name_.Destroy();
  _impl_.ipaddress_.Destroy();
  _impl_.sessiondata_.Destroy();
}

void ServerSession::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ServerSession::Clear() {
// @@protoc_insertion_point(message_clear_start:processService.ServerSession)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sessionproperties_.Clear();
  _impl_.serversessionid_.ClearToEmpty();
  _impl_.fleetid_.ClearToEmpty();
  _impl_.name_.ClearToEmpty();
  _impl_.ipaddress_.ClearToEmpty();
  _impl_.sessiondata_.ClearToEmpty();
  ::memset(&_impl_.maxclients_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.port_) -
      reinterpret_cast<char*>(&_impl_.maxclients_)) + sizeof(_impl_.port_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ServerSession::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string serverSessionId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_serversessionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.ServerSession.serverSessionId"));
        } else
          goto handle_unusual;
        continue;
      // string fleetId = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_fleetid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.ServerSession.fleetId"));
        } else
          goto handle_unusual;
        continue;
      // string name = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.ServerSession.name"));
        } else
          goto handle_unusual;
        continue;
      // int32 maxClients = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.maxclients_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool joinable = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.joinable_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .processService.SessionProperty sessionProperties = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_sessionproperties(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 port = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.port_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string ipAddress = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          auto str = _internal_mutable_ipaddress();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.ServerSession.ipAddress"));
        } else
          goto handle_unusual;
        continue;
      // string sessionData = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          auto str = _internal_mutable_sessiondata();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "processService.ServerSession.sessionData"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ServerSession::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:processService.ServerSession)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_serversessionid().data(), static_cast<int>(this->_internal_serversessionid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.ServerSession.serverSessionId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_serversessionid(), target);
  }

  // string fleetId = 2;
  if (!this->_internal_fleetid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_fleetid().data(), static_cast<int>(this->_internal_fleetid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.ServerSession.fleetId");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_fleetid(), target);
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.ServerSession.name");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_name(), target);
  }

  // int32 maxClients = 4;
  if (this->_internal_maxclients() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_maxclients(), target);
  }

  // bool joinable = 5;
  if (this->_internal_joinable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(5, this->_internal_joinable(), target);
  }

  // repeated .processService.SessionProperty sessionProperties = 6;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_sessionproperties_size()); i < n; i++) {
    const auto& repfield = this->_internal_sessionproperties(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(6, repfield, repfield.GetCachedSize(), target, stream);
  }

  // int32 port = 7;
  if (this->_internal_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_port(), target);
  }

  // string ipAddress = 8;
  if (!this->_internal_ipaddress().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_ipaddress().data(), static_cast<int>(this->_internal_ipaddress().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.ServerSession.ipAddress");
    target = stream->WriteStringMaybeAliased(
        8, this->_internal_ipaddress(), target);
  }

  // string sessionData = 9;
  if (!this->_internal_sessiondata().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sessiondata().data(), static_cast<int>(this->_internal_sessiondata().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "processService.ServerSession.sessionData");
    target = stream->WriteStringMaybeAliased(
        9, this->_internal_sessiondata(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:processService.ServerSession)
  return target;
}

size_t ServerSession::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:processService.ServerSession)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .processService.SessionProperty sessionProperties = 6;
  total_size += 1UL * this->_internal_sessionproperties_size();
  for (const auto& msg : this->_impl_.sessionproperties_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_serversessionid());
  }

  // string fleetId = 2;
  if (!this->_internal_fleetid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_fleetid());
  }

  // string name = 3;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string ipAddress = 8;
  if (!this->_internal_ipaddress().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ipaddress());
  }

  // string sessionData = 9;
  if (!this->_internal_sessiondata().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sessiondata());
  }

  // int32 maxClients = 4;
  if (this->_internal_maxclients() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_maxclients());
  }

  // bool joinable = 5;
  if (this->_internal_joinable() != 0) {
    total_size += 1 + 1;
  }

  // int32 port = 7;
  if (this->_internal_port() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_port());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ServerSession::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ServerSession::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ServerSession::GetClassData() const { return &_class_data_; }


void ServerSession::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ServerSession*>(&to_msg);
  auto& from = static_cast<const ServerSession&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:processService.ServerSession)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.sessionproperties_.MergeFrom(from._impl_.sessionproperties_);
  if (!from._internal_serversessionid().empty()) {
    _this->_internal_set_serversessionid(from._internal_serversessionid());
  }
  if (!from._internal_fleetid().empty()) {
    _this->_internal_set_fleetid(from._internal_fleetid());
  }
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_ipaddress().empty()) {
    _this->_internal_set_ipaddress(from._internal_ipaddress());
  }
  if (!from._internal_sessiondata().empty()) {
    _this->_internal_set_sessiondata(from._internal_sessiondata());
  }
  if (from._internal_maxclients() != 0) {
    _this->_internal_set_maxclients(from._internal_maxclients());
  }
  if (from._internal_joinable() != 0) {
    _this->_internal_set_joinable(from._internal_joinable());
  }
  if (from._internal_port() != 0) {
    _this->_internal_set_port(from._internal_port());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ServerSession::CopyFrom(const ServerSession& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:processService.ServerSession)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerSession::IsInitialized() const {
  return true;
}

void ServerSession::InternalSwap(ServerSession* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.sessionproperties_.InternalSwap(&other->_impl_.sessionproperties_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.serversessionid_, lhs_arena,
      &other->_impl_.serversessionid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.fleetid_, lhs_arena,
      &other->_impl_.fleetid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ipaddress_, lhs_arena,
      &other->_impl_.ipaddress_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sessiondata_, lhs_arena,
      &other->_impl_.sessiondata_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServerSession, _impl_.port_)
      + sizeof(ServerSession::_impl_.port_)
      - PROTOBUF_FIELD_OFFSET(ServerSession, _impl_.maxclients_)>(
          reinterpret_cast<char*>(&_impl_.maxclients_),
          reinterpret_cast<char*>(&other->_impl_.maxclients_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ServerSession::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[3]);
}

// ===================================================================

class StartServerSessionRequest::_Internal {
 public:
  static const ::processService::ServerSession& serversession(const StartServerSessionRequest* msg);
};

const ::processService::ServerSession&
StartServerSessionRequest::_Internal::serversession(const StartServerSessionRequest* msg) {
  return *msg->_impl_.serversession_;
}
StartServerSessionRequest::StartServerSessionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:processService.StartServerSessionRequest)
}
StartServerSessionRequest::StartServerSessionRequest(const StartServerSessionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  StartServerSessionRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.serversession_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_serversession()) {
    _this->_impl_.serversession_ = new ::processService::ServerSession(*from._impl_.serversession_);
  }
  // @@protoc_insertion_point(copy_constructor:processService.StartServerSessionRequest)
}

inline void StartServerSessionRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.serversession_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

StartServerSessionRequest::~StartServerSessionRequest() {
  // @@protoc_insertion_point(destructor:processService.StartServerSessionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void StartServerSessionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.serversession_;
}

void StartServerSessionRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void StartServerSessionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:processService.StartServerSessionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.serversession_ != nullptr) {
    delete _impl_.serversession_;
  }
  _impl_.serversession_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* StartServerSessionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .processService.ServerSession serverSession = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_serversession(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* StartServerSessionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:processService.StartServerSessionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .processService.ServerSession serverSession = 1;
  if (this->_internal_has_serversession()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::serversession(this),
        _Internal::serversession(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:processService.StartServerSessionRequest)
  return target;
}

size_t StartServerSessionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:processService.StartServerSessionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .processService.ServerSession serverSession = 1;
  if (this->_internal_has_serversession()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.serversession_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData StartServerSessionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    StartServerSessionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*StartServerSessionRequest::GetClassData() const { return &_class_data_; }


void StartServerSessionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<StartServerSessionRequest*>(&to_msg);
  auto& from = static_cast<const StartServerSessionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:processService.StartServerSessionRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_serversession()) {
    _this->_internal_mutable_serversession()->::processService::ServerSession::MergeFrom(
        from._internal_serversession());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void StartServerSessionRequest::CopyFrom(const StartServerSessionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:processService.StartServerSessionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool StartServerSessionRequest::IsInitialized() const {
  return true;
}

void StartServerSessionRequest::InternalSwap(StartServerSessionRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.serversession_, other->_impl_.serversession_);
}

::PROTOBUF_NAMESPACE_ID::Metadata StartServerSessionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[4]);
}

// ===================================================================

class ProcessTerminateRequest::_Internal {
 public:
};

ProcessTerminateRequest::ProcessTerminateRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:processService.ProcessTerminateRequest)
}
ProcessTerminateRequest::ProcessTerminateRequest(const ProcessTerminateRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProcessTerminateRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.terminationtime_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.terminationtime_ = from._impl_.terminationtime_;
  // @@protoc_insertion_point(copy_constructor:processService.ProcessTerminateRequest)
}

inline void ProcessTerminateRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.terminationtime_){int64_t{0}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProcessTerminateRequest::~ProcessTerminateRequest() {
  // @@protoc_insertion_point(destructor:processService.ProcessTerminateRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProcessTerminateRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProcessTerminateRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProcessTerminateRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:processService.ProcessTerminateRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.terminationtime_ = int64_t{0};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessTerminateRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int64 terminationTime = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.terminationtime_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessTerminateRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:processService.ProcessTerminateRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 terminationTime = 1;
  if (this->_internal_terminationtime() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(1, this->_internal_terminationtime(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:processService.ProcessTerminateRequest)
  return target;
}

size_t ProcessTerminateRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:processService.ProcessTerminateRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 terminationTime = 1;
  if (this->_internal_terminationtime() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_terminationtime());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessTerminateRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProcessTerminateRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessTerminateRequest::GetClassData() const { return &_class_data_; }


void ProcessTerminateRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProcessTerminateRequest*>(&to_msg);
  auto& from = static_cast<const ProcessTerminateRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:processService.ProcessTerminateRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_terminationtime() != 0) {
    _this->_internal_set_terminationtime(from._internal_terminationtime());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessTerminateRequest::CopyFrom(const ProcessTerminateRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:processService.ProcessTerminateRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessTerminateRequest::IsInitialized() const {
  return true;
}

void ProcessTerminateRequest::InternalSwap(ProcessTerminateRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.terminationtime_, other->_impl_.terminationtime_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessTerminateRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[5]);
}

// ===================================================================

class ProcessResponse::_Internal {
 public:
};

ProcessResponse::ProcessResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:processService.ProcessResponse)
}
ProcessResponse::ProcessResponse(const ProcessResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  ProcessResponse* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:processService.ProcessResponse)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessResponse::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata ProcessResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_process_5fgrpc_5fservice_2eproto_getter, &descriptor_table_process_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_process_5fgrpc_5fservice_2eproto[6]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace processService
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::processService::HealthCheckRequest*
Arena::CreateMaybeMessage< ::processService::HealthCheckRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::HealthCheckRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::HealthCheckResponse*
Arena::CreateMaybeMessage< ::processService::HealthCheckResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::HealthCheckResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::SessionProperty*
Arena::CreateMaybeMessage< ::processService::SessionProperty >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::SessionProperty >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::ServerSession*
Arena::CreateMaybeMessage< ::processService::ServerSession >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::ServerSession >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::StartServerSessionRequest*
Arena::CreateMaybeMessage< ::processService::StartServerSessionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::StartServerSessionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::ProcessTerminateRequest*
Arena::CreateMaybeMessage< ::processService::ProcessTerminateRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::ProcessTerminateRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::processService::ProcessResponse*
Arena::CreateMaybeMessage< ::processService::ProcessResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::processService::ProcessResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
