// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: auxproxy_grpc_service.proto

#include "auxproxy_grpc_service.pb.h"
#include "auxproxy_grpc_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace auxproxyService {

static const char* ScaseGrpcSdkService_method_names[] = {
  "/auxproxyService.ScaseGrpcSdkService/ProcessReady",
  "/auxproxyService.ScaseGrpcSdkService/ActivateServerSession",
  "/auxproxyService.ScaseGrpcSdkService/TerminateServerSession",
  "/auxproxyService.ScaseGrpcSdkService/ProcessEnding",
};

std::unique_ptr< ScaseGrpcSdkService::Stub> ScaseGrpcSdkService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ScaseGrpcSdkService::Stub> stub(new ScaseGrpcSdkService::Stub(channel, options));
  return stub;
}

ScaseGrpcSdkService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ProcessReady_(ScaseGrpcSdkService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ActivateServerSession_(ScaseGrpcSdkService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_TerminateServerSession_(ScaseGrpcSdkService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ProcessEnding_(ScaseGrpcSdkService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ScaseGrpcSdkService::Stub::ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::auxproxyService::AuxProxyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessReady_, context, request, response);
}

void ScaseGrpcSdkService::Stub::async::ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessReady_, context, request, response, std::move(f));
}

void ScaseGrpcSdkService::Stub::async::ProcessReady(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessReady_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::PrepareAsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auxproxyService::AuxProxyResponse, ::auxproxyService::ProcessReadyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessReady_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::AsyncProcessReadyRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessReadyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessReadyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ScaseGrpcSdkService::Stub::ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ActivateServerSession_, context, request, response);
}

void ScaseGrpcSdkService::Stub::async::ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActivateServerSession_, context, request, response, std::move(f));
}

void ScaseGrpcSdkService::Stub::async::ActivateServerSession(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ActivateServerSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::PrepareAsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auxproxyService::AuxProxyResponse, ::auxproxyService::ActivateServerSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ActivateServerSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::AsyncActivateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::ActivateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncActivateServerSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ScaseGrpcSdkService::Stub::TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::auxproxyService::AuxProxyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_TerminateServerSession_, context, request, response);
}

void ScaseGrpcSdkService::Stub::async::TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TerminateServerSession_, context, request, response, std::move(f));
}

void ScaseGrpcSdkService::Stub::async::TerminateServerSession(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_TerminateServerSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::PrepareAsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auxproxyService::AuxProxyResponse, ::auxproxyService::TerminateServerSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_TerminateServerSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::AsyncTerminateServerSessionRaw(::grpc::ClientContext* context, const ::auxproxyService::TerminateServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTerminateServerSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ScaseGrpcSdkService::Stub::ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::auxproxyService::AuxProxyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProcessEnding_, context, request, response);
}

void ScaseGrpcSdkService::Stub::async::ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessEnding_, context, request, response, std::move(f));
}

void ScaseGrpcSdkService::Stub::async::ProcessEnding(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProcessEnding_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::PrepareAsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::auxproxyService::AuxProxyResponse, ::auxproxyService::ProcessEndingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProcessEnding_, context, request);
}

::grpc::ClientAsyncResponseReader< ::auxproxyService::AuxProxyResponse>* ScaseGrpcSdkService::Stub::AsyncProcessEndingRaw(::grpc::ClientContext* context, const ::auxproxyService::ProcessEndingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessEndingRaw(context, request, cq);
  result->StartCall();
  return result;
}

ScaseGrpcSdkService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ScaseGrpcSdkService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ScaseGrpcSdkService::Service, ::auxproxyService::ProcessReadyRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ScaseGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auxproxyService::ProcessReadyRequest* req,
             ::auxproxyService::AuxProxyResponse* resp) {
               return service->ProcessReady(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ScaseGrpcSdkService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ScaseGrpcSdkService::Service, ::auxproxyService::ActivateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ScaseGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auxproxyService::ActivateServerSessionRequest* req,
             ::auxproxyService::AuxProxyResponse* resp) {
               return service->ActivateServerSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ScaseGrpcSdkService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ScaseGrpcSdkService::Service, ::auxproxyService::TerminateServerSessionRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ScaseGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auxproxyService::TerminateServerSessionRequest* req,
             ::auxproxyService::AuxProxyResponse* resp) {
               return service->TerminateServerSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ScaseGrpcSdkService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ScaseGrpcSdkService::Service, ::auxproxyService::ProcessEndingRequest, ::auxproxyService::AuxProxyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ScaseGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::auxproxyService::ProcessEndingRequest* req,
             ::auxproxyService::AuxProxyResponse* resp) {
               return service->ProcessEnding(ctx, req, resp);
             }, this)));
}

ScaseGrpcSdkService::Service::~Service() {
}

::grpc::Status ScaseGrpcSdkService::Service::ProcessReady(::grpc::ServerContext* context, const ::auxproxyService::ProcessReadyRequest* request, ::auxproxyService::AuxProxyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ScaseGrpcSdkService::Service::ActivateServerSession(::grpc::ServerContext* context, const ::auxproxyService::ActivateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ScaseGrpcSdkService::Service::TerminateServerSession(::grpc::ServerContext* context, const ::auxproxyService::TerminateServerSessionRequest* request, ::auxproxyService::AuxProxyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ScaseGrpcSdkService::Service::ProcessEnding(::grpc::ServerContext* context, const ::auxproxyService::ProcessEndingRequest* request, ::auxproxyService::AuxProxyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace auxproxyService

