// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auxproxy_grpc_service.proto

#include "auxproxy_grpc_service.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace auxproxyService {
PROTOBUF_CONSTEXPR ProcessReadyRequest::ProcessReadyRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.logpathstoupload_)*/{}
  , /*decltype(_impl_.clientport_)*/0
  , /*decltype(_impl_.grpcport_)*/0
  , /*decltype(_impl_.pid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProcessReadyRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessReadyRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessReadyRequestDefaultTypeInternal() {}
  union {
    ProcessReadyRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessReadyRequestDefaultTypeInternal _ProcessReadyRequest_default_instance_;
PROTOBUF_CONSTEXPR Error::Error(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.errorcode_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.errormsg_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ErrorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ErrorDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ErrorDefaultTypeInternal() {}
  union {
    Error _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ErrorDefaultTypeInternal _Error_default_instance_;
PROTOBUF_CONSTEXPR AuxProxyResponse::AuxProxyResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.error_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AuxProxyResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AuxProxyResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AuxProxyResponseDefaultTypeInternal() {}
  union {
    AuxProxyResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AuxProxyResponseDefaultTypeInternal _AuxProxyResponse_default_instance_;
PROTOBUF_CONSTEXPR ActivateServerSessionRequest::ActivateServerSessionRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.serversessionid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.maxclients_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ActivateServerSessionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ActivateServerSessionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ActivateServerSessionRequestDefaultTypeInternal() {}
  union {
    ActivateServerSessionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ActivateServerSessionRequestDefaultTypeInternal _ActivateServerSessionRequest_default_instance_;
PROTOBUF_CONSTEXPR TerminateServerSessionRequest::TerminateServerSessionRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.serversessionid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TerminateServerSessionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TerminateServerSessionRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TerminateServerSessionRequestDefaultTypeInternal() {}
  union {
    TerminateServerSessionRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TerminateServerSessionRequestDefaultTypeInternal _TerminateServerSessionRequest_default_instance_;
PROTOBUF_CONSTEXPR ProcessEndingRequest::ProcessEndingRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.pid_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProcessEndingRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessEndingRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessEndingRequestDefaultTypeInternal() {}
  union {
    ProcessEndingRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessEndingRequestDefaultTypeInternal _ProcessEndingRequest_default_instance_;
}  // namespace auxproxyService
static ::_pb::Metadata file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_auxproxy_5fgrpc_5fservice_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_auxproxy_5fgrpc_5fservice_2eproto = nullptr;

const uint32_t TableStruct_auxproxy_5fgrpc_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessReadyRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessReadyRequest, _impl_.logpathstoupload_),
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessReadyRequest, _impl_.clientport_),
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessReadyRequest, _impl_.grpcport_),
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessReadyRequest, _impl_.pid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::Error, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::Error, _impl_.errorcode_),
  PROTOBUF_FIELD_OFFSET(::auxproxyService::Error, _impl_.errormsg_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::AuxProxyResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::AuxProxyResponse, _impl_.error_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ActivateServerSessionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ActivateServerSessionRequest, _impl_.serversessionid_),
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ActivateServerSessionRequest, _impl_.maxclients_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::TerminateServerSessionRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::TerminateServerSessionRequest, _impl_.serversessionid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessEndingRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::auxproxyService::ProcessEndingRequest, _impl_.pid_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::auxproxyService::ProcessReadyRequest)},
  { 10, -1, -1, sizeof(::auxproxyService::Error)},
  { 18, -1, -1, sizeof(::auxproxyService::AuxProxyResponse)},
  { 25, -1, -1, sizeof(::auxproxyService::ActivateServerSessionRequest)},
  { 33, -1, -1, sizeof(::auxproxyService::TerminateServerSessionRequest)},
  { 40, -1, -1, sizeof(::auxproxyService::ProcessEndingRequest)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::auxproxyService::_ProcessReadyRequest_default_instance_._instance,
  &::auxproxyService::_Error_default_instance_._instance,
  &::auxproxyService::_AuxProxyResponse_default_instance_._instance,
  &::auxproxyService::_ActivateServerSessionRequest_default_instance_._instance,
  &::auxproxyService::_TerminateServerSessionRequest_default_instance_._instance,
  &::auxproxyService::_ProcessEndingRequest_default_instance_._instance,
};

const char descriptor_table_protodef_auxproxy_5fgrpc_5fservice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033auxproxy_grpc_service.proto\022\017auxproxyS"
  "ervice\"b\n\023ProcessReadyRequest\022\030\n\020logPath"
  "sToUpload\030\001 \003(\t\022\022\n\nclientPort\030\002 \001(\005\022\020\n\010g"
  "rpcPort\030\003 \001(\005\022\013\n\003pid\030\004 \001(\005\",\n\005Error\022\021\n\te"
  "rrorCode\030\001 \001(\t\022\020\n\010errorMsg\030\002 \001(\t\"9\n\020AuxP"
  "roxyResponse\022%\n\005error\030\001 \001(\0132\026.auxproxySe"
  "rvice.Error\"K\n\034ActivateServerSessionRequ"
  "est\022\027\n\017serverSessionId\030\001 \001(\t\022\022\n\nmaxClien"
  "ts\030\002 \001(\005\"8\n\035TerminateServerSessionReques"
  "t\022\027\n\017serverSessionId\030\001 \001(\t\"#\n\024ProcessEnd"
  "ingRequest\022\013\n\003pid\030\001 \001(\0052\251\003\n\023ScaseGrpcSdk"
  "Service\022Y\n\014ProcessReady\022$.auxproxyServic"
  "e.ProcessReadyRequest\032!.auxproxyService."
  "AuxProxyResponse\"\000\022k\n\025ActivateServerSess"
  "ion\022-.auxproxyService.ActivateServerSess"
  "ionRequest\032!.auxproxyService.AuxProxyRes"
  "ponse\"\000\022m\n\026TerminateServerSession\022..auxp"
  "roxyService.TerminateServerSessionReques"
  "t\032!.auxproxyService.AuxProxyResponse\"\000\022["
  "\n\rProcessEnding\022%.auxproxyService.Proces"
  "sEndingRequest\032!.auxproxyService.AuxProx"
  "yResponse\"\000B6\n\033io.grpc.examples.hellowor"
  "ldB\017HelloWorldProtoP\001\242\002\003HLWb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_auxproxy_5fgrpc_5fservice_2eproto = {
    false, false, 915, descriptor_table_protodef_auxproxy_5fgrpc_5fservice_2eproto,
    "auxproxy_grpc_service.proto",
    &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once, nullptr, 0, 6,
    schemas, file_default_instances, TableStruct_auxproxy_5fgrpc_5fservice_2eproto::offsets,
    file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto, file_level_enum_descriptors_auxproxy_5fgrpc_5fservice_2eproto,
    file_level_service_descriptors_auxproxy_5fgrpc_5fservice_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter() {
  return &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_auxproxy_5fgrpc_5fservice_2eproto(&descriptor_table_auxproxy_5fgrpc_5fservice_2eproto);
namespace auxproxyService {

// ===================================================================

class ProcessReadyRequest::_Internal {
 public:
};

ProcessReadyRequest::ProcessReadyRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.ProcessReadyRequest)
}
ProcessReadyRequest::ProcessReadyRequest(const ProcessReadyRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProcessReadyRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.logpathstoupload_){from._impl_.logpathstoupload_}
    , decltype(_impl_.clientport_){}
    , decltype(_impl_.grpcport_){}
    , decltype(_impl_.pid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.clientport_, &from._impl_.clientport_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.pid_) -
    reinterpret_cast<char*>(&_impl_.clientport_)) + sizeof(_impl_.pid_));
  // @@protoc_insertion_point(copy_constructor:auxproxyService.ProcessReadyRequest)
}

inline void ProcessReadyRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.logpathstoupload_){arena}
    , decltype(_impl_.clientport_){0}
    , decltype(_impl_.grpcport_){0}
    , decltype(_impl_.pid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProcessReadyRequest::~ProcessReadyRequest() {
  // @@protoc_insertion_point(destructor:auxproxyService.ProcessReadyRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProcessReadyRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.logpathstoupload_.~RepeatedPtrField();
}

void ProcessReadyRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProcessReadyRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.ProcessReadyRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.logpathstoupload_.Clear();
  ::memset(&_impl_.clientport_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.pid_) -
      reinterpret_cast<char*>(&_impl_.clientport_)) + sizeof(_impl_.pid_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessReadyRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string logPathsToUpload = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_logpathstoupload();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "auxproxyService.ProcessReadyRequest.logPathsToUpload"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // int32 clientPort = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.clientport_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 grpcPort = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.grpcport_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 pid = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.pid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessReadyRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.ProcessReadyRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string logPathsToUpload = 1;
  for (int i = 0, n = this->_internal_logpathstoupload_size(); i < n; i++) {
    const auto& s = this->_internal_logpathstoupload(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "auxproxyService.ProcessReadyRequest.logPathsToUpload");
    target = stream->WriteString(1, s, target);
  }

  // int32 clientPort = 2;
  if (this->_internal_clientport() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_clientport(), target);
  }

  // int32 grpcPort = 3;
  if (this->_internal_grpcport() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_grpcport(), target);
  }

  // int32 pid = 4;
  if (this->_internal_pid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_pid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.ProcessReadyRequest)
  return target;
}

size_t ProcessReadyRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.ProcessReadyRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string logPathsToUpload = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.logpathstoupload_.size());
  for (int i = 0, n = _impl_.logpathstoupload_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.logpathstoupload_.Get(i));
  }

  // int32 clientPort = 2;
  if (this->_internal_clientport() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_clientport());
  }

  // int32 grpcPort = 3;
  if (this->_internal_grpcport() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_grpcport());
  }

  // int32 pid = 4;
  if (this->_internal_pid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessReadyRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProcessReadyRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessReadyRequest::GetClassData() const { return &_class_data_; }


void ProcessReadyRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProcessReadyRequest*>(&to_msg);
  auto& from = static_cast<const ProcessReadyRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.ProcessReadyRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.logpathstoupload_.MergeFrom(from._impl_.logpathstoupload_);
  if (from._internal_clientport() != 0) {
    _this->_internal_set_clientport(from._internal_clientport());
  }
  if (from._internal_grpcport() != 0) {
    _this->_internal_set_grpcport(from._internal_grpcport());
  }
  if (from._internal_pid() != 0) {
    _this->_internal_set_pid(from._internal_pid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessReadyRequest::CopyFrom(const ProcessReadyRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.ProcessReadyRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessReadyRequest::IsInitialized() const {
  return true;
}

void ProcessReadyRequest::InternalSwap(ProcessReadyRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.logpathstoupload_.InternalSwap(&other->_impl_.logpathstoupload_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessReadyRequest, _impl_.pid_)
      + sizeof(ProcessReadyRequest::_impl_.pid_)
      - PROTOBUF_FIELD_OFFSET(ProcessReadyRequest, _impl_.clientport_)>(
          reinterpret_cast<char*>(&_impl_.clientport_),
          reinterpret_cast<char*>(&other->_impl_.clientport_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessReadyRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[0]);
}

// ===================================================================

class Error::_Internal {
 public:
};

Error::Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.Error)
}
Error::Error(const Error& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Error* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.errorcode_){}
    , decltype(_impl_.errormsg_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.errorcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.errorcode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_errorcode().empty()) {
    _this->_impl_.errorcode_.Set(from._internal_errorcode(), 
      _this->GetArenaForAllocation());
  }
  _impl_.errormsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.errormsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_errormsg().empty()) {
    _this->_impl_.errormsg_.Set(from._internal_errormsg(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:auxproxyService.Error)
}

inline void Error::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.errorcode_){}
    , decltype(_impl_.errormsg_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.errorcode_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.errorcode_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.errormsg_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.errormsg_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

Error::~Error() {
  // @@protoc_insertion_point(destructor:auxproxyService.Error)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Error::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.errorcode_.Destroy();
  _impl_.errormsg_.Destroy();
}

void Error::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Error::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.Error)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errorcode_.ClearToEmpty();
  _impl_.errormsg_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Error::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string errorCode = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_errorcode();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "auxproxyService.Error.errorCode"));
        } else
          goto handle_unusual;
        continue;
      // string errorMsg = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_errormsg();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "auxproxyService.Error.errorMsg"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Error::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.Error)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string errorCode = 1;
  if (!this->_internal_errorcode().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errorcode().data(), static_cast<int>(this->_internal_errorcode().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "auxproxyService.Error.errorCode");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_errorcode(), target);
  }

  // string errorMsg = 2;
  if (!this->_internal_errormsg().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_errormsg().data(), static_cast<int>(this->_internal_errormsg().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "auxproxyService.Error.errorMsg");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_errormsg(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.Error)
  return target;
}

size_t Error::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.Error)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string errorCode = 1;
  if (!this->_internal_errorcode().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_errorcode());
  }

  // string errorMsg = 2;
  if (!this->_internal_errormsg().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_errormsg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Error::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Error::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Error::GetClassData() const { return &_class_data_; }


void Error::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Error*>(&to_msg);
  auto& from = static_cast<const Error&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.Error)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_errorcode().empty()) {
    _this->_internal_set_errorcode(from._internal_errorcode());
  }
  if (!from._internal_errormsg().empty()) {
    _this->_internal_set_errormsg(from._internal_errormsg());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Error::CopyFrom(const Error& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Error::IsInitialized() const {
  return true;
}

void Error::InternalSwap(Error* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.errorcode_, lhs_arena,
      &other->_impl_.errorcode_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.errormsg_, lhs_arena,
      &other->_impl_.errormsg_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata Error::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[1]);
}

// ===================================================================

class AuxProxyResponse::_Internal {
 public:
  static const ::auxproxyService::Error& error(const AuxProxyResponse* msg);
};

const ::auxproxyService::Error&
AuxProxyResponse::_Internal::error(const AuxProxyResponse* msg) {
  return *msg->_impl_.error_;
}
AuxProxyResponse::AuxProxyResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.AuxProxyResponse)
}
AuxProxyResponse::AuxProxyResponse(const AuxProxyResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  AuxProxyResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_error()) {
    _this->_impl_.error_ = new ::auxproxyService::Error(*from._impl_.error_);
  }
  // @@protoc_insertion_point(copy_constructor:auxproxyService.AuxProxyResponse)
}

inline void AuxProxyResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.error_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

AuxProxyResponse::~AuxProxyResponse() {
  // @@protoc_insertion_point(destructor:auxproxyService.AuxProxyResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void AuxProxyResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.error_;
}

void AuxProxyResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void AuxProxyResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.AuxProxyResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.error_ != nullptr) {
    delete _impl_.error_;
  }
  _impl_.error_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* AuxProxyResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .auxproxyService.Error error = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* AuxProxyResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.AuxProxyResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .auxproxyService.Error error = 1;
  if (this->_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.AuxProxyResponse)
  return target;
}

size_t AuxProxyResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.AuxProxyResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .auxproxyService.Error error = 1;
  if (this->_internal_has_error()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.error_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData AuxProxyResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    AuxProxyResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*AuxProxyResponse::GetClassData() const { return &_class_data_; }


void AuxProxyResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<AuxProxyResponse*>(&to_msg);
  auto& from = static_cast<const AuxProxyResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.AuxProxyResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_error()) {
    _this->_internal_mutable_error()->::auxproxyService::Error::MergeFrom(
        from._internal_error());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void AuxProxyResponse::CopyFrom(const AuxProxyResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.AuxProxyResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuxProxyResponse::IsInitialized() const {
  return true;
}

void AuxProxyResponse::InternalSwap(AuxProxyResponse* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.error_, other->_impl_.error_);
}

::PROTOBUF_NAMESPACE_ID::Metadata AuxProxyResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[2]);
}

// ===================================================================

class ActivateServerSessionRequest::_Internal {
 public:
};

ActivateServerSessionRequest::ActivateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.ActivateServerSessionRequest)
}
ActivateServerSessionRequest::ActivateServerSessionRequest(const ActivateServerSessionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ActivateServerSessionRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.serversessionid_){}
    , decltype(_impl_.maxclients_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_serversessionid().empty()) {
    _this->_impl_.serversessionid_.Set(from._internal_serversessionid(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.maxclients_ = from._impl_.maxclients_;
  // @@protoc_insertion_point(copy_constructor:auxproxyService.ActivateServerSessionRequest)
}

inline void ActivateServerSessionRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.serversessionid_){}
    , decltype(_impl_.maxclients_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ActivateServerSessionRequest::~ActivateServerSessionRequest() {
  // @@protoc_insertion_point(destructor:auxproxyService.ActivateServerSessionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ActivateServerSessionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.serversessionid_.Destroy();
}

void ActivateServerSessionRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ActivateServerSessionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.ActivateServerSessionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.serversessionid_.ClearToEmpty();
  _impl_.maxclients_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActivateServerSessionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string serverSessionId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_serversessionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "auxproxyService.ActivateServerSessionRequest.serverSessionId"));
        } else
          goto handle_unusual;
        continue;
      // int32 maxClients = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.maxclients_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ActivateServerSessionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.ActivateServerSessionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_serversessionid().data(), static_cast<int>(this->_internal_serversessionid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "auxproxyService.ActivateServerSessionRequest.serverSessionId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_serversessionid(), target);
  }

  // int32 maxClients = 2;
  if (this->_internal_maxclients() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_maxclients(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.ActivateServerSessionRequest)
  return target;
}

size_t ActivateServerSessionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.ActivateServerSessionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_serversessionid());
  }

  // int32 maxClients = 2;
  if (this->_internal_maxclients() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_maxclients());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActivateServerSessionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ActivateServerSessionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActivateServerSessionRequest::GetClassData() const { return &_class_data_; }


void ActivateServerSessionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ActivateServerSessionRequest*>(&to_msg);
  auto& from = static_cast<const ActivateServerSessionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.ActivateServerSessionRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_serversessionid().empty()) {
    _this->_internal_set_serversessionid(from._internal_serversessionid());
  }
  if (from._internal_maxclients() != 0) {
    _this->_internal_set_maxclients(from._internal_maxclients());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActivateServerSessionRequest::CopyFrom(const ActivateServerSessionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.ActivateServerSessionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActivateServerSessionRequest::IsInitialized() const {
  return true;
}

void ActivateServerSessionRequest::InternalSwap(ActivateServerSessionRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.serversessionid_, lhs_arena,
      &other->_impl_.serversessionid_, rhs_arena
  );
  swap(_impl_.maxclients_, other->_impl_.maxclients_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ActivateServerSessionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[3]);
}

// ===================================================================

class TerminateServerSessionRequest::_Internal {
 public:
};

TerminateServerSessionRequest::TerminateServerSessionRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.TerminateServerSessionRequest)
}
TerminateServerSessionRequest::TerminateServerSessionRequest(const TerminateServerSessionRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TerminateServerSessionRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.serversessionid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_serversessionid().empty()) {
    _this->_impl_.serversessionid_.Set(from._internal_serversessionid(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:auxproxyService.TerminateServerSessionRequest)
}

inline void TerminateServerSessionRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.serversessionid_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.serversessionid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.serversessionid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TerminateServerSessionRequest::~TerminateServerSessionRequest() {
  // @@protoc_insertion_point(destructor:auxproxyService.TerminateServerSessionRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TerminateServerSessionRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.serversessionid_.Destroy();
}

void TerminateServerSessionRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TerminateServerSessionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.TerminateServerSessionRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.serversessionid_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TerminateServerSessionRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string serverSessionId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_serversessionid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "auxproxyService.TerminateServerSessionRequest.serverSessionId"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TerminateServerSessionRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.TerminateServerSessionRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_serversessionid().data(), static_cast<int>(this->_internal_serversessionid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "auxproxyService.TerminateServerSessionRequest.serverSessionId");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_serversessionid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.TerminateServerSessionRequest)
  return target;
}

size_t TerminateServerSessionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.TerminateServerSessionRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string serverSessionId = 1;
  if (!this->_internal_serversessionid().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_serversessionid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TerminateServerSessionRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TerminateServerSessionRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TerminateServerSessionRequest::GetClassData() const { return &_class_data_; }


void TerminateServerSessionRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TerminateServerSessionRequest*>(&to_msg);
  auto& from = static_cast<const TerminateServerSessionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.TerminateServerSessionRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_serversessionid().empty()) {
    _this->_internal_set_serversessionid(from._internal_serversessionid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TerminateServerSessionRequest::CopyFrom(const TerminateServerSessionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.TerminateServerSessionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TerminateServerSessionRequest::IsInitialized() const {
  return true;
}

void TerminateServerSessionRequest::InternalSwap(TerminateServerSessionRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.serversessionid_, lhs_arena,
      &other->_impl_.serversessionid_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata TerminateServerSessionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[4]);
}

// ===================================================================

class ProcessEndingRequest::_Internal {
 public:
};

ProcessEndingRequest::ProcessEndingRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:auxproxyService.ProcessEndingRequest)
}
ProcessEndingRequest::ProcessEndingRequest(const ProcessEndingRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProcessEndingRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.pid_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.pid_ = from._impl_.pid_;
  // @@protoc_insertion_point(copy_constructor:auxproxyService.ProcessEndingRequest)
}

inline void ProcessEndingRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.pid_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProcessEndingRequest::~ProcessEndingRequest() {
  // @@protoc_insertion_point(destructor:auxproxyService.ProcessEndingRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProcessEndingRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ProcessEndingRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProcessEndingRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:auxproxyService.ProcessEndingRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pid_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessEndingRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 pid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.pid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessEndingRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:auxproxyService.ProcessEndingRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 pid = 1;
  if (this->_internal_pid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_pid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:auxproxyService.ProcessEndingRequest)
  return target;
}

size_t ProcessEndingRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:auxproxyService.ProcessEndingRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 pid = 1;
  if (this->_internal_pid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessEndingRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProcessEndingRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessEndingRequest::GetClassData() const { return &_class_data_; }


void ProcessEndingRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProcessEndingRequest*>(&to_msg);
  auto& from = static_cast<const ProcessEndingRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:auxproxyService.ProcessEndingRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_pid() != 0) {
    _this->_internal_set_pid(from._internal_pid());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessEndingRequest::CopyFrom(const ProcessEndingRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:auxproxyService.ProcessEndingRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessEndingRequest::IsInitialized() const {
  return true;
}

void ProcessEndingRequest::InternalSwap(ProcessEndingRequest* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.pid_, other->_impl_.pid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessEndingRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_getter, &descriptor_table_auxproxy_5fgrpc_5fservice_2eproto_once,
      file_level_metadata_auxproxy_5fgrpc_5fservice_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace auxproxyService
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::auxproxyService::ProcessReadyRequest*
Arena::CreateMaybeMessage< ::auxproxyService::ProcessReadyRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::ProcessReadyRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::auxproxyService::Error*
Arena::CreateMaybeMessage< ::auxproxyService::Error >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::Error >(arena);
}
template<> PROTOBUF_NOINLINE ::auxproxyService::AuxProxyResponse*
Arena::CreateMaybeMessage< ::auxproxyService::AuxProxyResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::AuxProxyResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::auxproxyService::ActivateServerSessionRequest*
Arena::CreateMaybeMessage< ::auxproxyService::ActivateServerSessionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::ActivateServerSessionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::auxproxyService::TerminateServerSessionRequest*
Arena::CreateMaybeMessage< ::auxproxyService::TerminateServerSessionRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::TerminateServerSessionRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::auxproxyService::ProcessEndingRequest*
Arena::CreateMaybeMessage< ::auxproxyService::ProcessEndingRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::auxproxyService::ProcessEndingRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
