// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: process_grpc_service.proto

#include "process_grpc_service.pb.h"
#include "process_grpc_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace processService {

static const char* ProcessGrpcSdkService_method_names[] = {
  "/processService.ProcessGrpcSdkService/OnHealthCheck",
  "/processService.ProcessGrpcSdkService/OnStartServerSession",
  "/processService.ProcessGrpcSdkService/OnProcessTerminate",
};

std::unique_ptr< ProcessGrpcSdkService::Stub> ProcessGrpcSdkService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProcessGrpcSdkService::Stub> stub(new ProcessGrpcSdkService::Stub(channel, options));
  return stub;
}

ProcessGrpcSdkService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_OnHealthCheck_(ProcessGrpcSdkService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnStartServerSession_(ProcessGrpcSdkService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OnProcessTerminate_(ProcessGrpcSdkService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ProcessGrpcSdkService::Stub::OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::processService::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::processService::HealthCheckRequest, ::processService::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnHealthCheck_, context, request, response);
}

void ProcessGrpcSdkService::Stub::async::OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::processService::HealthCheckRequest, ::processService::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnHealthCheck_, context, request, response, std::move(f));
}

void ProcessGrpcSdkService::Stub::async::OnHealthCheck(::grpc::ClientContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnHealthCheck_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>* ProcessGrpcSdkService::Stub::PrepareAsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::processService::HealthCheckResponse, ::processService::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnHealthCheck_, context, request);
}

::grpc::ClientAsyncResponseReader< ::processService::HealthCheckResponse>* ProcessGrpcSdkService::Stub::AsyncOnHealthCheckRaw(::grpc::ClientContext* context, const ::processService::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnHealthCheckRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProcessGrpcSdkService::Stub::OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::processService::ProcessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::processService::StartServerSessionRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnStartServerSession_, context, request, response);
}

void ProcessGrpcSdkService::Stub::async::OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::processService::StartServerSessionRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnStartServerSession_, context, request, response, std::move(f));
}

void ProcessGrpcSdkService::Stub::async::OnStartServerSession(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnStartServerSession_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* ProcessGrpcSdkService::Stub::PrepareAsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::processService::ProcessResponse, ::processService::StartServerSessionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnStartServerSession_, context, request);
}

::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* ProcessGrpcSdkService::Stub::AsyncOnStartServerSessionRaw(::grpc::ClientContext* context, const ::processService::StartServerSessionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnStartServerSessionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ProcessGrpcSdkService::Stub::OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::processService::ProcessResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::processService::ProcessTerminateRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_OnProcessTerminate_, context, request, response);
}

void ProcessGrpcSdkService::Stub::async::OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::processService::ProcessTerminateRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnProcessTerminate_, context, request, response, std::move(f));
}

void ProcessGrpcSdkService::Stub::async::OnProcessTerminate(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_OnProcessTerminate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* ProcessGrpcSdkService::Stub::PrepareAsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::processService::ProcessResponse, ::processService::ProcessTerminateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_OnProcessTerminate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::processService::ProcessResponse>* ProcessGrpcSdkService::Stub::AsyncOnProcessTerminateRaw(::grpc::ClientContext* context, const ::processService::ProcessTerminateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOnProcessTerminateRaw(context, request, cq);
  result->StartCall();
  return result;
}

ProcessGrpcSdkService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProcessGrpcSdkService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProcessGrpcSdkService::Service, ::processService::HealthCheckRequest, ::processService::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProcessGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::processService::HealthCheckRequest* req,
             ::processService::HealthCheckResponse* resp) {
               return service->OnHealthCheck(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProcessGrpcSdkService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProcessGrpcSdkService::Service, ::processService::StartServerSessionRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProcessGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::processService::StartServerSessionRequest* req,
             ::processService::ProcessResponse* resp) {
               return service->OnStartServerSession(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProcessGrpcSdkService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProcessGrpcSdkService::Service, ::processService::ProcessTerminateRequest, ::processService::ProcessResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProcessGrpcSdkService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::processService::ProcessTerminateRequest* req,
             ::processService::ProcessResponse* resp) {
               return service->OnProcessTerminate(ctx, req, resp);
             }, this)));
}

ProcessGrpcSdkService::Service::~Service() {
}

::grpc::Status ProcessGrpcSdkService::Service::OnHealthCheck(::grpc::ServerContext* context, const ::processService::HealthCheckRequest* request, ::processService::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProcessGrpcSdkService::Service::OnStartServerSession(::grpc::ServerContext* context, const ::processService::StartServerSessionRequest* request, ::processService::ProcessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ProcessGrpcSdkService::Service::OnProcessTerminate(::grpc::ServerContext* context, const ::processService::ProcessTerminateRequest* request, ::processService::ProcessResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace processService

